name: Backend tests

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.8'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        virtualenv env
        .\\env\Scripts\activate
        pip install -r src/requirements.txt
        pip install pyinstaller
    - name: Create exe from python
      run: |
        .\env\Scripts\pyinstaller -F  main.spec
    - name: Test exe from python
      run: |
        .\dist\main.exe
    - name: Setup nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Create exe from electron
      run: |
        cd view-app
        npm install
        npm install -g electron-packager --save-dev
        electron-packager . tonation --platform=win32 --arch=x64 --overwrite
        cd ..
    - name: Prepare release
      run: |
        cp main.exe view-app\tonation-win32-x64\
        mkdir view-app\tonation-win32-x64\data\temp
        powershell Compress-Archive -Path view-app\tonation-win32-x64 -DestinationPath app.zip
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        draft: true
        files: |
          app.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # You don't need to add this in secrets it's by default.

